/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTeamsIndexRouteImport } from './routes/dashboard/teams/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthGoogleIndexRouteImport } from './routes/auth/google/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/auth/forgot-password/index'
import { Route as TeamTeamIdTeammatesIndexRouteImport } from './routes/team/$teamId/teammates/index'
import { Route as TeamTeamIdTasksIndexRouteImport } from './routes/team/$teamId/tasks/index'
import { Route as TeamTeamIdChatIndexRouteImport } from './routes/team/$teamId/chat/index'
import { Route as TeamTeamIdAcceptinvationIndexRouteImport } from './routes/team/$teamId/acceptinvation/index'
import { Route as DashboardTeamsCreateIndexRouteImport } from './routes/dashboard/teams/create/index'
import { Route as DashboardTasksCalendarIndexRouteImport } from './routes/dashboard/tasks/calendar/index'
import { Route as TeamTeamIdLeaderTaskIndexRouteImport } from './routes/team/$teamId/leader/task/index'
import { Route as TeamTeamIdLeaderSettingsIndexRouteImport } from './routes/team/$teamId/leader/settings/index'
import { Route as TeamTeamIdTasksViewTaskIdIndexRouteImport } from './routes/team/$teamId/tasks/view/$taskId/index'

const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamsIndexRoute = DashboardTeamsIndexRouteImport.update({
  id: '/dashboard/teams/',
  path: '/dashboard/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/dashboard/settings/',
  path: '/dashboard/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/auth/reset-password/',
  path: '/auth/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleIndexRoute = AuthGoogleIndexRouteImport.update({
  id: '/auth/google/',
  path: '/auth/google/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/auth/forgot-password/',
  path: '/auth/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdTeammatesIndexRoute =
  TeamTeamIdTeammatesIndexRouteImport.update({
    id: '/team/$teamId/teammates/',
    path: '/team/$teamId/teammates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdTasksIndexRoute = TeamTeamIdTasksIndexRouteImport.update({
  id: '/team/$teamId/tasks/',
  path: '/team/$teamId/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdChatIndexRoute = TeamTeamIdChatIndexRouteImport.update({
  id: '/team/$teamId/chat/',
  path: '/team/$teamId/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdAcceptinvationIndexRoute =
  TeamTeamIdAcceptinvationIndexRouteImport.update({
    id: '/team/$teamId/acceptinvation/',
    path: '/team/$teamId/acceptinvation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTeamsCreateIndexRoute =
  DashboardTeamsCreateIndexRouteImport.update({
    id: '/dashboard/teams/create/',
    path: '/dashboard/teams/create/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTasksCalendarIndexRoute =
  DashboardTasksCalendarIndexRouteImport.update({
    id: '/dashboard/tasks/calendar/',
    path: '/dashboard/tasks/calendar/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdLeaderTaskIndexRoute =
  TeamTeamIdLeaderTaskIndexRouteImport.update({
    id: '/team/$teamId/leader/task/',
    path: '/team/$teamId/leader/task/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdLeaderSettingsIndexRoute =
  TeamTeamIdLeaderSettingsIndexRouteImport.update({
    id: '/team/$teamId/leader/settings/',
    path: '/team/$teamId/leader/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdTasksViewTaskIdIndexRoute =
  TeamTeamIdTasksViewTaskIdIndexRouteImport.update({
    id: '/team/$teamId/tasks/view/$taskId/',
    path: '/team/$teamId/tasks/view/$taskId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/google': typeof AuthGoogleIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/teams': typeof DashboardTeamsIndexRoute
  '/dashboard/tasks/calendar': typeof DashboardTasksCalendarIndexRoute
  '/dashboard/teams/create': typeof DashboardTeamsCreateIndexRoute
  '/team/$teamId/acceptinvation': typeof TeamTeamIdAcceptinvationIndexRoute
  '/team/$teamId/chat': typeof TeamTeamIdChatIndexRoute
  '/team/$teamId/tasks': typeof TeamTeamIdTasksIndexRoute
  '/team/$teamId/teammates': typeof TeamTeamIdTeammatesIndexRoute
  '/team/$teamId/leader/settings': typeof TeamTeamIdLeaderSettingsIndexRoute
  '/team/$teamId/leader/task': typeof TeamTeamIdLeaderTaskIndexRoute
  '/team/$teamId/tasks/view/$taskId': typeof TeamTeamIdTasksViewTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/google': typeof AuthGoogleIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/teams': typeof DashboardTeamsIndexRoute
  '/dashboard/tasks/calendar': typeof DashboardTasksCalendarIndexRoute
  '/dashboard/teams/create': typeof DashboardTeamsCreateIndexRoute
  '/team/$teamId/acceptinvation': typeof TeamTeamIdAcceptinvationIndexRoute
  '/team/$teamId/chat': typeof TeamTeamIdChatIndexRoute
  '/team/$teamId/tasks': typeof TeamTeamIdTasksIndexRoute
  '/team/$teamId/teammates': typeof TeamTeamIdTeammatesIndexRoute
  '/team/$teamId/leader/settings': typeof TeamTeamIdLeaderSettingsIndexRoute
  '/team/$teamId/leader/task': typeof TeamTeamIdLeaderTaskIndexRoute
  '/team/$teamId/tasks/view/$taskId': typeof TeamTeamIdTasksViewTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/google/': typeof AuthGoogleIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/teams/': typeof DashboardTeamsIndexRoute
  '/dashboard/tasks/calendar/': typeof DashboardTasksCalendarIndexRoute
  '/dashboard/teams/create/': typeof DashboardTeamsCreateIndexRoute
  '/team/$teamId/acceptinvation/': typeof TeamTeamIdAcceptinvationIndexRoute
  '/team/$teamId/chat/': typeof TeamTeamIdChatIndexRoute
  '/team/$teamId/tasks/': typeof TeamTeamIdTasksIndexRoute
  '/team/$teamId/teammates/': typeof TeamTeamIdTeammatesIndexRoute
  '/team/$teamId/leader/settings/': typeof TeamTeamIdLeaderSettingsIndexRoute
  '/team/$teamId/leader/task/': typeof TeamTeamIdLeaderTaskIndexRoute
  '/team/$teamId/tasks/view/$taskId/': typeof TeamTeamIdTasksViewTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feedback'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/google'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/dashboard/settings'
    | '/dashboard/teams'
    | '/dashboard/tasks/calendar'
    | '/dashboard/teams/create'
    | '/team/$teamId/acceptinvation'
    | '/team/$teamId/chat'
    | '/team/$teamId/tasks'
    | '/team/$teamId/teammates'
    | '/team/$teamId/leader/settings'
    | '/team/$teamId/leader/task'
    | '/team/$teamId/tasks/view/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feedback'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/google'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/dashboard/settings'
    | '/dashboard/teams'
    | '/dashboard/tasks/calendar'
    | '/dashboard/teams/create'
    | '/team/$teamId/acceptinvation'
    | '/team/$teamId/chat'
    | '/team/$teamId/tasks'
    | '/team/$teamId/teammates'
    | '/team/$teamId/leader/settings'
    | '/team/$teamId/leader/task'
    | '/team/$teamId/tasks/view/$taskId'
  id:
    | '__root__'
    | '/'
    | '/feedback'
    | '/dashboard/'
    | '/auth/forgot-password/'
    | '/auth/google/'
    | '/auth/login/'
    | '/auth/reset-password/'
    | '/auth/signup/'
    | '/dashboard/settings/'
    | '/dashboard/teams/'
    | '/dashboard/tasks/calendar/'
    | '/dashboard/teams/create/'
    | '/team/$teamId/acceptinvation/'
    | '/team/$teamId/chat/'
    | '/team/$teamId/tasks/'
    | '/team/$teamId/teammates/'
    | '/team/$teamId/leader/settings/'
    | '/team/$teamId/leader/task/'
    | '/team/$teamId/tasks/view/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedbackRoute: typeof FeedbackRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthGoogleIndexRoute: typeof AuthGoogleIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardTeamsIndexRoute: typeof DashboardTeamsIndexRoute
  DashboardTasksCalendarIndexRoute: typeof DashboardTasksCalendarIndexRoute
  DashboardTeamsCreateIndexRoute: typeof DashboardTeamsCreateIndexRoute
  TeamTeamIdAcceptinvationIndexRoute: typeof TeamTeamIdAcceptinvationIndexRoute
  TeamTeamIdChatIndexRoute: typeof TeamTeamIdChatIndexRoute
  TeamTeamIdTasksIndexRoute: typeof TeamTeamIdTasksIndexRoute
  TeamTeamIdTeammatesIndexRoute: typeof TeamTeamIdTeammatesIndexRoute
  TeamTeamIdLeaderSettingsIndexRoute: typeof TeamTeamIdLeaderSettingsIndexRoute
  TeamTeamIdLeaderTaskIndexRoute: typeof TeamTeamIdLeaderTaskIndexRoute
  TeamTeamIdTasksViewTaskIdIndexRoute: typeof TeamTeamIdTasksViewTaskIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teams/': {
      id: '/dashboard/teams/'
      path: '/dashboard/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/': {
      id: '/auth/google/'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/teammates/': {
      id: '/team/$teamId/teammates/'
      path: '/team/$teamId/teammates'
      fullPath: '/team/$teamId/teammates'
      preLoaderRoute: typeof TeamTeamIdTeammatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/tasks/': {
      id: '/team/$teamId/tasks/'
      path: '/team/$teamId/tasks'
      fullPath: '/team/$teamId/tasks'
      preLoaderRoute: typeof TeamTeamIdTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/chat/': {
      id: '/team/$teamId/chat/'
      path: '/team/$teamId/chat'
      fullPath: '/team/$teamId/chat'
      preLoaderRoute: typeof TeamTeamIdChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/acceptinvation/': {
      id: '/team/$teamId/acceptinvation/'
      path: '/team/$teamId/acceptinvation'
      fullPath: '/team/$teamId/acceptinvation'
      preLoaderRoute: typeof TeamTeamIdAcceptinvationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teams/create/': {
      id: '/dashboard/teams/create/'
      path: '/dashboard/teams/create'
      fullPath: '/dashboard/teams/create'
      preLoaderRoute: typeof DashboardTeamsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tasks/calendar/': {
      id: '/dashboard/tasks/calendar/'
      path: '/dashboard/tasks/calendar'
      fullPath: '/dashboard/tasks/calendar'
      preLoaderRoute: typeof DashboardTasksCalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/leader/task/': {
      id: '/team/$teamId/leader/task/'
      path: '/team/$teamId/leader/task'
      fullPath: '/team/$teamId/leader/task'
      preLoaderRoute: typeof TeamTeamIdLeaderTaskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/leader/settings/': {
      id: '/team/$teamId/leader/settings/'
      path: '/team/$teamId/leader/settings'
      fullPath: '/team/$teamId/leader/settings'
      preLoaderRoute: typeof TeamTeamIdLeaderSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/tasks/view/$taskId/': {
      id: '/team/$teamId/tasks/view/$taskId/'
      path: '/team/$teamId/tasks/view/$taskId'
      fullPath: '/team/$teamId/tasks/view/$taskId'
      preLoaderRoute: typeof TeamTeamIdTasksViewTaskIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedbackRoute: FeedbackRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthGoogleIndexRoute: AuthGoogleIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardTeamsIndexRoute: DashboardTeamsIndexRoute,
  DashboardTasksCalendarIndexRoute: DashboardTasksCalendarIndexRoute,
  DashboardTeamsCreateIndexRoute: DashboardTeamsCreateIndexRoute,
  TeamTeamIdAcceptinvationIndexRoute: TeamTeamIdAcceptinvationIndexRoute,
  TeamTeamIdChatIndexRoute: TeamTeamIdChatIndexRoute,
  TeamTeamIdTasksIndexRoute: TeamTeamIdTasksIndexRoute,
  TeamTeamIdTeammatesIndexRoute: TeamTeamIdTeammatesIndexRoute,
  TeamTeamIdLeaderSettingsIndexRoute: TeamTeamIdLeaderSettingsIndexRoute,
  TeamTeamIdLeaderTaskIndexRoute: TeamTeamIdLeaderTaskIndexRoute,
  TeamTeamIdTasksViewTaskIdIndexRoute: TeamTeamIdTasksViewTaskIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
